project:
  type: website
  render:
    - "*.qmd"
    - "publications/**/*.qmd"
    - "!publications/_template/"
    - "posts/**/*.qmd"
  output-dir: docs

# Meta
description-meta: "McCall Research Group Website"
author-meta: "Dr. Matthew N. McCall"

website:
  title: "McCall Research Group"
  image: "https://quarto.org/quarto.png"
  description: "McCall Research Group Website"
 
  navbar:
    background: light

    left:
      - text: Home
        href: index.qmd
      - text: People
        href: people.qmd
      - text: Publications
        href: publications/index.qmd
      - text: News
        href: posts.qmd
#      - text: Teaching
#        href: teaching.qmd
#      - text: Outreach
#        menu:        
#        - text: Presentations
#          href: posts.qmd#category=presentation                   


    right: 
      - text: CV
        href: files/mccall_cv.pdf
      - icon: github
        href: https://github.com/mccallm
        target: _blank
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/matthewnmccall.bsky.social
        target: _blank      
  
  page-navigation: true
  
  page-footer: 
    left: "[Matthew N. McCall](http://www.github.com/mccallm) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Build on [Quarto Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) adapted by [Dr. Gang He](http://drganghe.github.io)"
    right:  
      - icon: github
        href: https://github.com/mccallm
        target: _blank
      - text: "{{< fa brands bluesky >}}" 
        href: https://bsky.app/profile/matthewnmccall.bsky.social
        target: _blank
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/mccallm/mccallm.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://mccallm.github.io"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/mccallm\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

